---
- name: Create CNI directory
  ansible.builtin.file:
    path: "{{ k8s.cni.folder }}"
    state: directory
    mode: 0755

- name: Get CNI
  get_url:
    url: "{{ k8s.cni.url }}{{ k8s.cni.version }}/cni-plugins-linux-amd64-{{ k8s.cni.version }}.tgz"
    dest: /tmp/cni.tar.gz

- name: Uncompress CNI
  ansible.builtin.unarchive:
    src: /tmp/cni.tar.gz
    dest: "{{ k8s.cni.folder }}"
    remote_src: yes

- name: Create CRI directory
  ansible.builtin.file:
    path: "{{ k8s.cri.folder }}"
    state: directory
    mode: 0755

- name: Get CRI
  get_url:
    url: "{{ k8s.cri.url }}{{ k8s.cri.version }}/crictl-{{ k8s.cri.version }}-linux-amd64.tar.gz"
    dest: /tmp/cri.tar.gz

- name: Uncompress CRI
  ansible.builtin.unarchive:
    src: /tmp/cri.tar.gz
    dest: "{{ k8s.cri.folder }}"
    remote_src: yes