---
- name: Add the kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ k8s.kernel.modules }}"

- name: Create file module conf
  ansible.builtin.file:
    path: "{{ k8s.files.module_load }}"
    state: touch
    mode: 0644
  changed_when: False

- name: Ensure modules loads are in file
  lineinfile:
    path: "{{ k8s.files.module_load }}"
    state: present
    regexp: '^{{ item }}.*'
    line: "{{ item }}"
  with_items: "{{ k8s.kernel.modules }}"

- name: Create file sysctl.d config
  ansible.builtin.file:
    path: "{{ k8s.files.sysctl_bridge }}"
    state: touch
    mode: 0644
  changed_when: False

- name: Ensure net configs are in file
  lineinfile:
    path: "{{ k8s.files.sysctl_bridge }}"
    state: present
    regexp: '^{{ item }}.*'
    line: "{{ item }}"
  with_items: "{{ k8s.network_config }}"