---
# handlers file for kubeadm_install
- name: Containerd Service Enable
  ansible.builtin.systemd:
    name: containerd.service
    state: started
    daemon_reload: yes
    enabled: yes

- name: Kubelet Service Enable
  ansible.builtin.systemd:
    name: kubelet.service
    state: started
    daemon_reload: yes
    enabled: yes