---
# handlers file for kubeadm_install
- name: Containerd Service Enable
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes

- name: Kubelet Service Enable
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: yes